version: '3.4'

services:
  web1:
    image: app
    build: .
    ports:
      - 5000:5000
    environment:
      FLASK_PORT: 5000

  web2:
    image: app
    build: .
    ports:
      - 5005:5005
    environment:
      FLASK_PORT: 5005



