version: '3.3'

services:
  web1:
    ports:
      - 5001:5001
    environment:
      FLASK_PORT: 5001

  web3:
    image: app
    build: .
    ports:
      - 5010:5010
    environment:
      FLASK_PORT: 5010

