version: '3.3'

services:
  web1:
    image: app
    build: .
    ports:
      - 5000:5000
    environment:
      FLASK_PORT: 5000

  web2:
    image: app
    build: .
    ports:
      - 5003:5003
    environment:
      FLASK_PORT: 5003



